# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7v585tffg1157-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Ain_shams/GP/Synthesis/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Ain_shams/GP/Synthesis/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Ain_shams/GP/Synthesis/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/bus_matrix/bus_matrix_defs.v
  C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/ahb_peripherals/apb_subsystem/dual_timer/cmsdk_apb_dualtimers_defs.v
  C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/ahb_peripherals/apb_subsystem/watchdog/cmsdk_apb_watchdog_defs.v
}
set_property file_type "Verilog Header" [get_files C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/bus_matrix/bus_matrix_defs.v]
set_property file_type "Verilog Header" [get_files C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/ahb_peripherals/apb_subsystem/dual_timer/cmsdk_apb_dualtimers_defs.v]
set_property file_type "Verilog Header" [get_files C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/ahb_peripherals/apb_subsystem/watchdog/cmsdk_apb_watchdog_defs.v]
read_verilog -library xil_defaultlib {
  C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/bus_matrix/AHB_Arbiter.v
  C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/bus_matrix/AHB_BusMatrix.v
  C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/bus_matrix/AHB_BusMatrix_default_slave.v
  C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/bus_matrix/AHB_BusMatrix_lite.v
  C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/bus_matrix/AHB_DecoderStageS0.v
  C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/bus_matrix/AHB_InputStage.v
  C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/bus_matrix/AHB_OutputStage.v
  C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/ahb_peripherals/apb_subsystem/bridge/APB_Bridge.v
  C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/ahb_peripherals/apb_subsystem/subsystem_top/APB_decoder.v
  C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/ahb_peripherals/rcc/CLKDIV.v
  C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/ahb_peripherals/rcc/CLK_GATE.v
  C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/cortex/CORTEXM0INTEGRATION.v
  C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/ahb_peripherals/memory/DATA_SRAM_TOP.v
  C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/ahb_peripherals/gpio/GPIO_HW.v
  C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/ahb_peripherals/memory/Instruction_SRAM_TOP.v
  C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/ahb_peripherals/rcc/RCC.v
  C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/ahb_peripherals/rcc/RESET_SYNC.v
  C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/ahb_peripherals/gpio/cmsdk_ahb_gpio.v
  C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/ahb_peripherals/memory/cmsdk_ahb_to_dsram.v
  C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/ahb_peripherals/gpio/cmsdk_ahb_to_iop.v
  C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/ahb_peripherals/memory/cmsdk_ahb_to_isram.v
  C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/ahb_peripherals/apb_subsystem/dual_timer/cmsdk_apb_dualtimers.v
  C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/ahb_peripherals/apb_subsystem/dual_timer/cmsdk_apb_dualtimers_frc.v
  C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/ahb_peripherals/apb_subsystem/subsystem_top/cmsdk_apb_slave_mux.v
  C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/ahb_peripherals/apb_subsystem/subsystem_top/cmsdk_apb_subsystem.v
  C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/ahb_peripherals/apb_subsystem/timer/cmsdk_apb_timer.v
  C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/ahb_peripherals/apb_subsystem/uart/cmsdk_apb_uart.v
  C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/ahb_peripherals/apb_subsystem/watchdog/cmsdk_apb_watchdog.v
  C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/ahb_peripherals/apb_subsystem/watchdog/cmsdk_apb_watchdog_frc.v
  C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/ahb_peripherals/memory/cmsdk_fpga_dsram.v
  C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/ahb_peripherals/memory/cmsdk_fpga_isram.v
  C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/ahb_peripherals/gpio/cmsdk_iop_gpio.v
  C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/ahb_peripherals/apb_subsystem/subsystem_top/cmsdk_irq_sync.v
  C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/cortex/cortexm0ds_logic.v
  C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/ahb_peripherals/gpio/mux_2x1.v
  C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/ahb_peripherals/gpio/tri_state_buffer.v
  C:/Ain_shams/GP/Synthesis/project_1/project_1.srcs/sources_1/imports/RTL/top/SYSTEM_TOP.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top SYSTEM_TOP -part xc7v585tffg1157-3 -flatten_hierarchy none


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef SYSTEM_TOP.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file SYSTEM_TOP_utilization_synth.rpt -pb SYSTEM_TOP_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
